services:
    victoire_core.widget_login_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Login }

    #alias to the entity
    victoire.widget.login:
        class: Victoire\Widget\LoginBundle\Entity\WidgetLogin

    #alias to the form
    victoire.widget.form.login:
        class: Victoire\Widget\LoginBundle\Form\WidgetLoginType
        tags:
            - { name: form.type , alias: victoire_widget_form_login }
